### ISSUE TITLE
Possibly wrong logic for compression block count

### ISSUE THREAD

**Issue by HakanL** [Cryptkeeper/fseq-file-format#1]
I see you have example code for the compression block count:
`uint16_t extendedCompressionBlockCount = (compressionType & 0xF0) | compressionBlockCount;
`
but that doesn't match the description of using 12 bits and the compressionType having the upper 4 bits for the block count. It needs to be shifted by 4 instead of AND:d if I interpret it correctly.

**Comment by Cryptkeeper** [comment]
Pushed* a few comments to fix this error. Thanks for the catch! Let me know if anything else stands out. The docs are due for some re-organizing.

**Comment by HakanL** [comment]
Looks good, thanks!
